### ISSUE TITLE
Error in { : task 1 failed - "could not find function "randomForest""

### ISSUE THREAD

**Issue by deepunamb** [qx0731/ensemble_forecast_methods#1]
Hi, this code is not running.. whenever I run the demo.r , it shows this error...it also shows the same error for xgboost function as well.. please either tell the procedure how to run this code..or please tell me how to rectify this error...

**Comment by qx0731** [comment]
Thanks for trying the package and submitting this question. 

This error looks like an R and R-package configuration issue. Please verify the random forest library is correctly installed and loaded.

**Comment by deepunamb** [comment]
No Sir, I've installed the randomForest package correctly before itself, and still it is not running..

**Comment by deepunamb** [comment]
You can see Sir, in this screenshot, I ran the code only after installing the package.. it didn't work. And is there any problem if RStudio is used, instead of R? ANd which version of R did you use when you created this? 
![screenshot 46](https://user-images.githubusercontent.com/40245761/41373919-549ead00-6f6f-11e8-9873-7ca0f9b93179.png)

**Comment by qx0731** [comment]
This package is years behind me. Currently, I don't have the bandwidth and development environment to help you debug this.  please google the error.
For example: https://stackoverflow.com/questions/30017847/while-creating-a-random-forest-using-foreach-in-r-i-am-getting-error-cannot

By this way, it is not Sir :). Be aware of unconscious bias.

**Comment by deepunamb** [comment]
Well, I'm sorry for calling you Sir, but I didn't get you actually, what did you mean...? Did you mean that I wont be able to run it directly by using this package? If so, how can I run it then? 
And the link you gave me above, I searched for the solution in Google and I saw that thread, but couldn't possibly make any changes to your program using that... It wasn't of any help to me. 

Please help me out Sir, I'm in very need of it. And besides, how are you currently going to run this code in your pc? If this package doesn't work for me, then it shouldn't be possibly working for you as well, isn't it? If you want to run it now, how ae you gonna run it on your pc? Share your knowledge with me please if possible.
